In [114]:
import numpy as np
import matplotlib.pyplot as plt


In [115]:
def sigmoid(z):
    return 1 / (1 + np.exp(-z))
print(sigmoid(np.array([1,2])))

[0.73105858 0.88079708]


In [116]:
train = np.array([[ 0.346 , 0.780 ] , [ 0.303 , 0.439 ] , [0.358 , 0.729 ] , [0.602 , 0.863] , [0.790 , 0.753 ] , [0.611 , 0.965] ], dtype = float)

train_label = np.array([0,0,0,1,1,1], dtype=float)

test = np.array([[0.959,0.382],[0.75,0.306],[0.395,0.760],[0.823,0.764],[0.761,0.874],[0.844,0.435]], dtype = float)

test_label = np.array([0,0,0,1,1,1], dtype = float)


In [117]:
X = np.c_[np.ones(6) , train]
X_test = np.c_[np.ones(6), test]
print(X)

[[1.    0.346 0.78 ]
 [1.    0.303 0.439]
 [1.    0.358 0.729]
 [1.    0.602 0.863]
 [1.    0.79  0.753]
 [1.    0.611 0.965]]


In [118]:
class logisticRegression:
    def __init__(self) -> None:
        self.W = None

    def learn(self, X, y, epoch=5000 , w = None, learning_rate = 0.01) -> np.array:
        n, m  = X.shape
        if w is None:
            w = np.zeros(m)
        for _ in range(epoch):
            dw = np.matmul(sigmoid(np.matmul(w,X.T)) - y , X)
            dw = dw / n
            w = w - learning_rate*dw
        self.W = w
    
    def predict(self, X) -> np.array:
         return np.round_(sigmoid(np.matmul(self.W,X.T)))

    
            
            



In [119]:
clf = logisticRegression()
clf.learn(X, train_label)
print("for train data")
print("predicted labels: ",clf.predict(X))
print("actual labels: ",train_label)
print("for test data")
print("predicted labels: ",clf.predict(X_test))
print("actual labels: ",test_label)
print("Four labels correct")


for train data
predicted labels:  [0. 0. 0. 1. 1. 1.]
actual labels:  [0. 0. 0. 1. 1. 1.]
for test data
predicted labels:  [1. 1. 0. 1. 1. 1.]
actual labels:  [0. 0. 0. 1. 1. 1.]
Four labels correct
