In [1]:
import numpy as np
import matplotlib.pyplot as plt


In [2]:
def sigmoid(z):
    return 1 / (1 + np.exp(-z))
print(sigmoid(np.array([1,2])))

[0.73105858 0.88079708]


In [3]:
train = np.array([[1,1 ],[1,0],[0,0] ], dtype = float)

train_label = np.array([1,-1,1], dtype=float)

test = np.array([[0.959,0.382],[0.75,0.306],[0.395,0.760],[0.823,0.764],[0.761,0.874],[0.844,0.435]], dtype = float)

test_label = np.array([0,0,0,1,1,1], dtype = float)


In [5]:
X = np.c_[np.ones(3) , train]
X_test = np.c_[np.ones(6), test]
print(X)

[[1. 1. 1.]
 [1. 1. 0.]
 [1. 0. 0.]]


In [ ]:
class logisticRegression:
    def __init__(self) -> None:
        self.W = None

    def learn(self, X, y, tolerance = 0.1, w = None, learning_rate = 0.1) -> np.array:
        n, m  = X.shape
        if w is None:
            w = np.zeros(m)
        ctr = 1
        while True: 
            dw = np.matmul(sigmoid(np.matmul(w,X.T)) - y , X)
            dw = dw / n
            w = w - learning_rate*dw
            if np.linalg.norm(dw) < tolerance:
                break 
            if ctr:
                print(w)
                ctr = 0
        self.W = w
        print(self.W)
    
    def predict(self, X) -> np.array:
         return np.round_(sigmoid(np.matmul(self.W,X.T)))

    
            
            



In [9]:
clf = logisticRegression()
w=np.array([-1,1.5,0.5])
clf.learn(X, train_label,w=w )
print("for train data")
print("predicted labels: ",clf.predict(X))
print("actual labels: ",train_label)
# print("for test data")
# print("predicted labels: ",clf.predict(X_test))
# print("actual labels: ",test_label)
# print("Four labels correct")


[-1.02074864  1.45488274  0.50896471]


<ipython-input-2-48d3f2916af7>:2: RuntimeWarning: overflow encountered in exp
  return 1 / (1 + np.exp(-z))


KeyboardInterrupt: 

In [17]:
accuracy = sum( clf.predict(X_test) == test_label)/len(test_label)

In [18]:

print(accuracy)

0.6666666666666666


In [23]:
L = clf.predict(X_test)
tp, fn , fp, tn = 0 , 0 , 0 , 0
for i in range(len(L)):
    if L[i] == 1:
        if test_label[i] == 1:
            tp += 1
        else:
            fp += 1
    if L[i] == 0:
        if test_label[i] == 0:
            tn += 1
        else:
            fn += 1
precision = tp/(tp+fp)
recall = tp/(tp+fn)
print('precision:',precision,'\n recall', recall)
    

precision: 0.6 
 recall 1.0
